version: '2'
services:
    interview-app:
        image: interview
        external_links:
            - interview-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/interview
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    interview-postgresql:
        extends:
            file: postgresql.yml
            service: interview-postgresql
